"""create users information

Revision ID: 0f3c4032f8fe
Revises: 
Create Date: 2024-02-06 19:16:31.400293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3c4032f8fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_information')
    # ### end Alembic commands ###
