"""add slogan to user information

Revision ID: 28ee85b8981f
Revises: 957e385bcf23
Create Date: 2024-03-22 11:41:39.336223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ee85b8981f'
down_revision: Union[str, None] = '957e385bcf23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_information', sa.Column('slogan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_information', 'slogan')
    # ### end Alembic commands ###
